name: flutter_todolist
description: Todo List.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  flutter_overlay_loader: ^1.0.3
  flutter_signin_button: ^2.0.0
  google_fonts: ^2.2.0
  google_sign_in: ^5.2.3
  intl: ^0.17.0
  path: ^1.8.0
  provider: ^5.0.0
  sqflite: ^2.0.0+4
  validatorless: ^1.2.1
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/LexendDeca-Black.ttf
        - asset: assets/fonts/LexendDeca-Bold.ttf
        - asset: assets/fonts/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/LexendDeca-ExtraLight.ttf
        - asset: assets/fonts/LexendDeca-Light.ttf
        - asset: assets/fonts/LexendDeca-Medium.ttf
        - asset: assets/fonts/LexendDeca-Regular.ttf
        - asset: assets/fonts/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/LexendDeca-Thin.ttf
    
    - family: TodoListIcon
      fonts:
        - asset: assets/fonts/TodoListIcon.ttf
